# Generated by Django 4.2.24 on 2025-09-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_user_id_8dce99_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_created_03e07d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
